application: jeddit-grevian
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /favicon\.ico
  static_files: resources/static/favicon.ico
  upload: resources/static/favicon\.ico

- url: /logo\.png
  static_files: resources/static/logo.png
  upload: resources/static/logo\.png

- url: /resources/static
  static_dir: resources/static

- url: /vote/.*
  script: vote.VOTE_APP

- url: /.*
  script: index.APP

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

